# Encoding 설정
server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# DBMS 설정
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE  # Oracle DB URL
    driver-class-name: oracle.jdbc.OracleDriver  # Oracle JDBC 드라이버
    username: BONG  
    password: 1234 
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:repository/*.xml  # XML 파일 경로
  type-aliases-package: com.bong.board.domain.dto  # DTO 패키지 경로

logging:
  level:
    com.bong.board.util.LoggerInterceptor: DEBUG



  